### ISSUE TITLE
crearte a calculator using python

### ISSUE THREAD

**Issue by MryashAditya007** [MryashAditya007/Open_for_Contributors#5]
Path [Open_for_Contributors/Python/](https://github.com/MryashAditya007/Open_for_Contributors/tree/main/Python)

**Comment by chiragkhatri19** [comment]
Hello, I am a graphics designer. Can I create some graphics or banner for your readme file and if yes please make a new issue with same description and assign that to me. I'll happily contribute

**Comment by raginiisingh** [comment]
Hey can you please assign me this issue

**Comment by MryashAditya007** [comment]
> Hey can you please assign me this issue

@raginiisingh Sure.

**Comment by MryashAditya007** [comment]
> Hello, I am a graphics designer. Can I create some graphics or banner for your readme file and if yes please make a new issue with same description and assign that to me. I'll happily contribute

@chiragkhatri19 Yes, you can please check new issue.

**Comment by MryashAditya007** [comment]
> Hello, I am a graphics designer. Can I create some graphics or banner for your readme file and if yes please make a new issue with same description and assign that to me. I'll happily contribute

@chiragkhatri19 Yes you can, please check new issue.

**Comment by Vivekumar01** [comment]
I would like to work on this issue please assign me this issue.

**Comment by MryashAditya007** [comment]
> I would like to work on this issue please assign me this issue.

@Viveakhumar01 I have assigned to you

**Comment by Vivekumar01** [comment]
I have added a calculator. Please check my pull request and merge

**Comment by MryashAditya007** [comment]
> I have added a calculator. Please check my pull request and merge

@Vivekumar01 Well done!!
